# usecases/usecase2/schemas.py

from typing import List, Optional
from pydantic import BaseModel, Field
from enum import Enum

# Import shared enums and agent output types from UC1
# WIA and MAA outputs are identical — no need to redefine them
from usecases.usecase1.schemas import (
    RiskClassification,
    RecommendationTrigger,
    ConfidenceLevel,
    WIAOutput,
    MAAOutput,
)


# ============================================================
# USER INPUT — Policy Intent (replaces UseCase1Input)
# ============================================================

class OptimizationPriority(str, Enum):
    MINIMIZE_RISK    = "minimize_risk"    # safest scenario wins
    MINIMIZE_COST    = "minimize_cost"    # lowest budget stress wins
    MINIMIZE_TIME    = "minimize_time"    # shortest timeline wins
    BALANCED         = "balanced"         # overall best tradeoff wins


class PolicyIntent(BaseModel):
    """
    What the user submits for Use Case 2.
    Much simpler than UC1 — no constraints, no full policy description.
    The SGA generates the scenarios and their constraints automatically.
    """
    sector: str                          # e.g. "healthcare"
    policy_goal: str                     # e.g. "Expand healthcare workforce"
    target_growth_pct: float = Field(..., ge=1, le=100)  # e.g. 20 (meaning 20%)
    priority: OptimizationPriority = OptimizationPriority.BALANCED


# ============================================================
# SGA OUTPUT — One generated scenario
# ============================================================

class ScenarioSpec(BaseModel):
    """
    A single scenario as generated by the SGA.
    Each has its own name, rationale, and constraint set.
    These feed directly into the UC1 pipeline agents (WIA, MAA).
    """
    scenario_id: str                    # "A", "B", "C"
    name: str                           # e.g. "Accelerated Expansion"
    rationale: str                      # Why this strategy makes sense
    time_horizon: str                   # "short" | "medium" | "long"
    budget_limit: float = Field(..., ge=0, le=1)       # maps to UC1 Constraints
    workforce_capacity: float = Field(..., ge=0, le=1) # maps to UC1 Constraints
    training_investment: bool           # does this scenario invest in training?
    key_tradeoff: str                   # e.g. "Speed vs. sustainability"


# ============================================================
# PIPELINE RESULT — Full output for one scenario
# ============================================================

class ScenarioPAAOutput(BaseModel):
    """Lightweight PAA output for a scenario — no LLM call needed, derived from spec."""
    scenario_id: str
    policy_objectives: List[str]
    affected_domains: List[str]
    complexity_level: str
    explanation: str                    # short description of this scenario's approach


class ScenarioResult(BaseModel):
    """Complete evaluation of a single scenario through the pipeline."""
    spec: ScenarioSpec
    paa_output: ScenarioPAAOutput
    wia_output: WIAOutput
    maa_output: MAAOutput


# ============================================================
# CAA OUTPUT — Comparative Assessment
# ============================================================

class ScenarioRanking(BaseModel):
    """How one scenario ranked in the comparison."""
    scenario_id: str
    rank: int                           # 1 = best
    overall_score: float = Field(..., ge=0, le=100)   # 0-100, higher = better
    recommendation: str                 # "Recommended" | "Acceptable" | "Not Recommended"
    strengths: List[str]
    weaknesses: List[str]


class CAAOutput(BaseModel):
    """Full comparative assessment across all scenarios."""
    rankings: List[ScenarioRanking]
    best_scenario_id: str               # e.g. "C"
    comparison_narrative: str           # LLM-generated written analysis
    conditions_statement: str           # "Scenario B becomes preferable if..."
    hybrid_recommended: bool            # Should ORA generate a hybrid?
    explanation: str                    # LLM summary of why this ranking was produced


# ============================================================
# ORA OUTPUT — Hybrid Synthesis (UC2 mode)
# ============================================================

class HybridScenario(BaseModel):
    """A synthesized policy that combines best elements of top scenarios."""
    name: str                           # e.g. "Capability-Led Phased Expansion"
    description: str                    # What this hybrid does
    derived_from: List[str]             # e.g. ["B", "C"] — which scenarios it combines
    time_horizon: str
    budget_limit: float
    workforce_capacity: float
    training_investment: bool
    expected_risk_level: str            # "Low" | "Moderate" | "High"
    expected_severity_estimate: float   # rough estimate 0-100
    key_advantages: List[str]
    implementation_steps: List[str]


class UC2ORAOutput(BaseModel):
    hybrid_scenario: HybridScenario
    explanation: str                    # LLM narrative explaining the synthesis


# ============================================================
# UC2 FINAL RESPONSE
# ============================================================

class UC2FinalResponse(BaseModel):
    use_case: str                       # "Policy Scenario Comparison"
    sector: str
    policy_goal: str
    priority: str

    # All three scenario results
    scenario_results: List[ScenarioResult]

    # Comparative assessment
    caa_output: CAAOutput

    # Hybrid recommendation (always generated for UC2)
    ora_output: UC2ORAOutput

    # Top-level recommendation
    recommended_scenario_id: str        # "A", "B", "C", or "HYBRID"
    executive_summary: str

    # Which agents ran
    agents_activated: List[str]         # ["SGA", "PAA", "WIA", "MAA", "CAA", "ORA"]

    # Metadata
    simulation_id: str
    elapsed_seconds: float